version: '3'

services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    container_name: vueblog-naginx
    ports:
      - "80:80"  # 暴露端口
    volumes: # 挂载
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
    restart: always

  mysql:
    image: mysql:5.7
    container_name: vueblog-mysql
    volumes:
      - /usr/local/docker/mysql/conf:/etc/mysql/conf.d
      - /usr/local/docker/mysql/data:/var/lib/mysql
      - /usr/local/docker/mysql/logs:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  redis:
    image: redis:latest
    container_name: vueblog-redis
    ports:
      - "6379:6379"
    restart: always

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: vueblog-elasticsearch
    volumes:
      - /usr/local/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - /usr/local/docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /usr/local/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /usr/local/docker/elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms64m -Xmx256m"
      - discovery.type=single-node
    privileged: true
    restart: always

  canal-server:
    image: canal/canal-server:v1.1.5
    container_name: vueblog-canal-server
    volumes:
      - /usr/local/docker/canal-server/logs:/admin/canal-server/logs/
    ports:
      - "11111:11111"
    environment:
      - canal.instance.mysql.slaveId=2
      - canal.instance.master.address=vueblog-mysql:3306
      # mysql 复制账号
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=root
    restart: always

  canal-adapter:
    image: slpcat/canal-adapter:v1.1.5
    container_name: vueblog-canal-adapter
    volumes:
      - /usr/local/docker/canal-adapter/config/application.yml:/opt/canal-adapter/conf/application.yml
      - /usr/local/docker/canal-adapter/es7:/opt/canal-adapter/conf/es7
    ports:
      - "8082:8082"
    restart: always

  vueblog:
    image: vueblog:latest
    container_name: vueblog
    volumes:
      - /usr/local/docker/vueblog:/usr/data
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
      - elasticsearch
    restart: always