version: '3'

services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - 80:80  # 暴露端口
    volumes: # 挂载
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
    restart: always

  mysql:
    image: mysql:5.7
    volumes:
      - /usr/local/docker/mysql/conf:/etc/mysql/conf.d
      - /usr/local/docker/mysql/data:/var/lib/mysql
      - /usr/local/docker/mysql/logs:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  redis:
    image: redis:latest
    restart: always

  vueblog:
    image: vueblog:latest
    volumes:
      - /usr/local/docker/vueblog:/usr/data
    build: .
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - redis
    restart: always