spring:
  profiles:
    active: prd
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # springboot升级2.6.0导致的

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

vueblog:
  jwt:
    #加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #token有效期，1天，单位秒
    expire: 86400
