#不使用docker镜像仓库
name: VueBlog CI
on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java
    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@master
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Build
        run: mvn -B -DskipTests=true package --file pom.xml

      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.USER_HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASS }}
          concurrency: 20
          local: target/vueblog-0.0.1-SNAPSHOT.jar
          remote: /usr/local/docker/vueblog/vueblog-0.0.1-SNAPSHOT.jar

      - name: Docker Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.USER_HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASS }}
          script: |
            docker restart vueblog