name: VueBlog CI
on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java
    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@master
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Build
        run: mvn -B -DskipTests=true package --file pom.xml

      # 构建多平台
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 初始化构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 开始构建 在当前目录下找Dockerfile,也可以指定Dockerfile位置
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # 当前工作目录
          context: .
          # 构建完成后 push
          push: true
          # github账号 tag
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vueblog:latest

      - name: Docker Pull and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.USER_HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASS }}
          script: |
            cd ~
            nohup ./vueblog_start.sh &
            tail -f nohup.out